---
# We need sudo for some of the Docker commands.
sudo: required

env:
  # Provide a list of OSes we want to use for testing.
  - distro: centos6

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

before_install:
  # Pull the image from Docker Hub for the OS under test.
  - 'docker pull geerlingguy/docker-${distro}-ansible:latest'

script:

  - wget -O ${PWD}/tests/test.sh https://gist.github.com/soroushatarod/55218a5d24bc6c889836249719318ebd

  - chmod +x ${PWD}/tests/test.sh

  - ${PWD}/tests/test.sh

notifications:
  # Notify Ansible Galaxy when a role builds successfully.