---
- hosts: all
  become: yes
  vars:
    mysql_root_password: 98_Av&%Ac54
    wordpress_database_name: wordpress
    mysql_wordpress_username: wordpress_db
    mysql_wordpress_password: 28_Av&%Ac54
  roles:
    - apache
    - mysql
    - php
    - wordpress
